### ISSUE TITLE
Suggest new UI components

### ISSUE THREAD

**Issue by Frenziecodes** [Frenziecodes/Aurora-ComKit#2]
We're always looking for ways to improve our library of UI components built with Tailwind CSS, and we would love to hear your suggestions for new components that we can add.

If you have an idea for a new component that you think would be useful, please let us know by leaving a comment on this issue. Here are some things to consider when proposing a new component:

What is the purpose of the component? What problem does it solve?
What props or classes would be needed to customize the component?
Are there any existing components that are similar to what you're proposing?
We appreciate your input and look forward to hearing your ideas. Thank you for helping us make our library even better!

**Comment by Shalini469717** [comment]
In the testimonials section, maybe we can add carousel type testimonials? Just a suggestion.

**Comment by Frenziecodes** [comment]
@Shalini469717  yes that's a great idea. Do you want want to work on it ?

**Comment by Shalini469717** [comment]
I don't know how to do it using CSS, I made one using Bootstrap before

**Comment by Frenziecodes** [comment]
@Shalini469717  can you share the code on issue #7  so that i can change it to tailwindCss ?

**Comment by Shalini469717** [comment]
I used the one present in the documentation of bootstrap
Checkout this part of the documentation
https://getbootstrap.com/docs/5.3/components/carousel/

**Comment by gabrysia694** [comment]
In the navbar section, we could add vertical display (there's horizontal one already) and a dropdown menu?

**Comment by debasish-dutta** [comment]
There are very less navbar components. How about adding a couple more?
Like one with a dropdown or a search bar?
Or maybe one with a profile menu dropdown?

**Comment by Frenziecodes** [comment]
Great, @gabrysia694! I plan to include a vertical display and a dropdown menu shortly. Do you happen to have one already?

**Comment by Frenziecodes** [comment]
Thank you @debasish-dutta  for your suggestion! I appreciate your feedback on the current navbar components available. Adding more options, such as a navbar with a dropdown or search bar, or a navbar with a profile menu dropdown, is definitely something worth considering. I'll keep your ideas in mind as I work on expanding our component library.

**Comment by SoundaryaKoutharapu** [comment]
@lewisushindi  I am interested to contribute to nav bar components like animated nav bar/ bottom nav bar.
 If you are already working on them please let me know.

**Comment by SoundaryaKoutharapu** [comment]
And also how about adding new UI components like **progress bars**.

**Comment by Frenziecodes** [comment]
@SoundaryaKoutharapu Thank you for showing interest , you can work on the navbar components.

**Comment by gabrysia694** [comment]
> Great, @gabrysia694! I plan to include a vertical display and a dropdown menu shortly. Do you happen to have one already?

I don't have any at the moment but I'll be happy to work on that unless you've already got them ready to add
