### ISSUE TITLE
The icons in the footer are not aligned in the center of page

### ISSUE THREAD

**Issue by Shalini469717** [Frenziecodes/Aurora-ComKit#3]
**Describe the bug**
The icons in the footer are not aligned in the center

**Expected behavior**
The icons would be in the center of the page

**Screenshots**
![image](https://user-images.githubusercontent.com/99305545/229525446-55a3cb78-2c77-41eb-bdb9-67c474e7928a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by Shalini469717** [comment]
I found out the problem can I make a pull request?

**Comment by Frenziecodes** [comment]
sure @Shalini469717 you can make a pull request of this issue

**Comment by Shalini469717** [comment]
yes!

**Comment by Shalini469717** [comment]
#4

**Comment by Shalini469717** [comment]
#5

**Comment by Frenziecodes** [comment]
completed by @Shalini469717
