### ISSUE TITLE
No footer in the forms page

### ISSUE THREAD

**Issue by Shalini469717** [Frenziecodes/Aurora-ComKit#6]
**Describe the bug**
There is no footer in the forms page

**Expected behavior**
Adding footer to the form page

**Screenshots**
![image](https://user-images.githubusercontent.com/99305545/229712186-55c772c1-dcf7-4acc-bc8f-a1da1fe7a2e6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Shalini469717** [comment]
Noticed it while working on the icons issue. Shall I add the footer?

**Comment by Frenziecodes** [comment]
yeah ! Go ahead and add the footer @Shalini469717

**Comment by Shalini469717** [comment]
#8

**Comment by Frenziecodes** [comment]
merged the pull request. Thank you !
